from string import Template

ControllerTemplate = Template(
r"""import { Mutable } from 'savitri/dist/backend'
import { ${pascal_case}Document, ${pascal_case} } from './${camel_case}.model'
import { default as Description } from './index.json'

/**
    @remarks Generated by savitrigen
    @copyright Protolab Systems
    ${documentation}
*/

export class ${pascal_case}Controller extends Mutable<${pascal_case}Document> {
  constructor() {
    super(${pascal_case}, Description)
  }
}
""")

ModelTemplate = Template(
r"""import { mongoose, options, descriptionToSchema } from 'savitri/dist/backend'
import { default as Description } from './index.json'

${document_imports}
${reference_imports}

export interface ${pascal_case}Document extends mongoose.Document {
${type_hints}
}

export const ${pascal_case}Schema = descriptionToSchema<${pascal_case}Document>(Description, options)
export const ${pascal_case} = mongoose.model<${pascal_case}Document>('${pascal_case}', ${pascal_case}Schema)
""")

DocumentImportTemplate = Template(r"import { ${pascal_case}Document } from '../${camel_case}/${camel_case}.model'")

ReferenceImportTemplate = Template(r"import '../${camel_case}/${camel_case}.model'")
